name: get_cli_tutorial
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  get: 4.6.6
  intl: ^0.19.0
  awesome_notifications: ^0.9.3+1

  get_storage: ^2.1.1
  flutter_launcher_icons: ^0.14.1
  timezone: ^0.9.4
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/ss.gif